SELECT m.MOVIENO, m.TITLE, m.RATINGCODE, r.SHORTDESC, m.TMDB_SCORE FROM MOVIE6811 m
INNER JOIN RATING6811 r ON m.RATINGCODE = r.RATINGCODE
WHERE (m.TMDB_SCORE BETWEEN 6.5 AND 7.5) AND (m.RATINGCODE = 'MA' AND (m.RUNTIME BETWEEN 100 AND 102)
OR (m.RATINGCODE = 'G' AND (m.RUNTIME <= 90))
OR (m.RATINGCODE = 'PG' AND (m.RUNTIME BETWEEN 120 AND 125))
OR (m.RATINGCODE = 'M' AND m.RUNTIME >= 180))
ORDER BY m.MOVIENO ASC