SELECT m.MOVIENO, m.TITLE, m.RUNTIME, m.TMDB_SCORE, r.LONGDESC FROM MOVIE6811 m
INNER JOIN RATING6811 r ON m.RATINGCODE = r.RATINGCODE
WHERE UPPER(r.LONGDESC) LIKE '%RECOMMENDED%'
OR m.TMDB_ID LIKE '%44%'
OR UPPER(m.TITLE) LIKE '%T%'