-- a)
--UPDATE MOVIE6811 
--SET TMDB_VOTES = 0

-- b)
--UPDATE MOVIE6811
--SET TMDB_VOTES = 1
--WHERE (RUNTIME >= 180 AND RATINGCODE = 'M')
--OR RUNTIME >= 160 AND RATINGCODE = 'MA'

-- c)
SELECT m.MOVIENO, m.TITLE, m.RELYEAR, m.RUNTIME, m.RATINGCODE FROM MOVIE6811 m
WHERE m.TMDB_VOTES = 1
ORDER BY m.TITLE ASC
